stages:
- stage: Build
  jobs:
  - job: Build
    variables:
      build.clean: all
      platform: x64
      version: "current"
      appVersion: "1.0"
      appBuild: $[counter(variables['appVersion'],0)]
      appRevision: 0
      createRuntimePackages: False
      skipComponentGovernanceDetection: True

    pool:
      name: Default

    steps:
    - task: PowerShell@2
      displayName: 'Reading Settings'
      inputs:
        targetType: filePath
        filePath: 'scripts\Read-Settings.ps1'
        arguments: '-appVersion "$(appVersion).$(appBuild).$(appRevision)"'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Login to bcinsider repository'
      condition: and(succeeded(),or(eq(variables['version'],'nextminor'),
                 eq(variables['version'],'nextmajor')))
      inputs:
        targetType: inline
        script: 'docker login "bcinsider.azurecr.io" -u "$(bcInsiderUsername)"
                 -p "$(bcinsiderPassword)"'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Install NavContainerHelper'
      inputs:
        targetType: filePath
        filePath: 'scripts\Install-NavContainerHelper.ps1'
        failOnStderr: true